# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70924b16a4c1030e36bb5625d745124abe7ad1c5b4e40e5c8b6ad8d11922f7acfbc8690055621daafba50f3965c5e3eba5f6db659c6457de88ecff7a6d2fc657

test:
  secret_key_base: 60779a34517db390f2af4fc8024c6101de8557a87aafc04fb3d72361c8a62b7da5b42492c744c67f2af5196e348e70eb3479694482d57c4b8082aef665ce69f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
